name: khudrah_companies
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.0-nullsafety
  easy_localization: ^3.0.0
  pin_code_fields: ^7.3.0
  flutter_pin_code_fields: ^1.1.0
  retrofit: any
  json_annotation: any
  logger: any
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.9
  geolocator: ^8.0.1
  geocoding: ^2.0.1
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.10
  font_awesome_flutter: ^9.2.0
  another_flushbar: ^1.10.28
  lottie: ^1.2.1
  provider: ^4.1.2
  flutter_slidable: ^1.2.0
  sliding_up_panel: ^2.0.0+1
  firebase_core: ^1.12.0
  firebase_dynamic_links: ^4.0.5

dev_dependencies:
  retrofit_generator: any
  json_serializable: any
  build_runner: any
  flutter_test:
    sdk: flutter



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/locale/lang/

  fonts:
    - family: Almarai
      fonts:
        - asset: fonts/Almarai-Regular.ttf
  #       - fonts/Almarai-Bold.ttf
  #       - fonts/Almarai-ExtraBold.ttf
  #       - fonts/Almarai-Light.ttf
        
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
