const String homeRoute = "home";
const String aboutRoute = "about";
const String settingsRoute = "settings";
const String loginRoute = "login";
const String signupRoute = "signup";
const String welcomeRoute = "welcome";
const String languageRoute = "language";
const String noPage="noPage";
const String editInfoRoute="editInfo";